# Generated by Django 2.2.12 on 2021-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('extremedroite', models.CharField(max_length=250)),
                ('data_tondeuse1', models.CharField(max_length=250)),
                ('sequence1', models.CharField(max_length=250)),
                ('sequence2', models.CharField(max_length=250)),
                ('sequence3', models.CharField(max_length=250)),
            ],
        ),
    ]
