# Generated by Django 2.2.12 on 2021-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='data_tondeuse2',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='partie',
            name='data_tondeuse3',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
