# Generated by Django 2.2.12 on 2021-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210213_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='data_tondeuse2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partie',
            name='data_tondeuse3',
            field=models.CharField(max_length=250),
        ),
    ]
