# Generated by Django 2.2.12 on 2021-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210213_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='sortie1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='partie',
            name='sortie2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='partie',
            name='sortie3',
            field=models.CharField(default='', max_length=250),
        ),
    ]
