# Generated by Django 2.2.12 on 2021-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210213_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='sortie1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partie',
            name='sortie2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partie',
            name='sortie3',
            field=models.CharField(max_length=250),
        ),
    ]
